Add support to set and reset volume options
kadalu/moana pull request #171
Opened 2022-03-29 06:29 UTC by vatsa287

Fixes: #76 
Signed-off-by: Shree Vatsa N <vatsa@kadalu.io>

2022-04-01 10:39 UTC, aravindavk requested changes
Remove the Print statements from the code.

2022-04-01 10:39 UTC, aravindavk commented on clients/crystal/src/volumes.cr
> +    def set(volume_options : String)
Accept `Hash(String, String)` here.

2022-04-01 10:39 UTC, aravindavk commented on clients/crystal/src/volumes.cr
> +        ({"volume_options": volume_options}).to_json,
directly send input options. `volume_options.to_json`

2022-04-01 10:39 UTC, aravindavk commented on clients/crystal/src/volumes.cr
> +    def reset(volume_option_keys : Array)
Same here. Accept `Array(String)`

2022-04-01 10:39 UTC, aravindavk commented on clients/crystal/src/volumes.cr
> +        ({"volume_option_keys": volume_option_keys}).to_json,
directly send the input option keys. `volume_option_keys.to_json`

2022-04-01 10:39 UTC, aravindavk commented on mgr/src/cmds/helpers.cr
> +  end
Line 136-142

```
volume_options.each_slice(2) do |opt|
  vol_opts[opt[0]] = opt[1]
end
```

2022-04-01 10:39 UTC, aravindavk commented on mgr/src/cmds/volumes.cr
> +    volume = client.pool(args.pool_name).volume(volume_name).set(volume_options.to_json.to_s)
```
volume = client.pool(args.pool_name).volume(volume_name).set(volume_options)
```

2022-04-01 10:39 UTC, aravindavk commented on mgr/src/server/plugins/volume_option_set_reset.cr
> +  volume_options = env.params.json["volume_options"].as(String)
```
volume_options = Hash(String, String).from_json(env.request.body.not_nil!)
```

2022-04-01 10:39 UTC, aravindavk commented on mgr/src/server/plugins/volume_option_set_reset.cr
> +  volume.options = volume.options.merge(Hash(String, String).from_json(volume_options))
```
volume.options = volume.options.merge(volume_options)
```

2022-04-01 10:39 UTC, aravindavk commented on mgr/src/server/plugins/volume_option_set_reset.cr
> +  Datastore.update_volume_options(volume.id, volume.options.to_json.to_s)
`.to_s` is redundant. `to_json` itself convert to string format.

2022-04-01 10:39 UTC, aravindavk commented on mgr/src/server/plugins/volume_option_set_reset.cr
> +  Datastore.update_volume_options(volume.id, volume.options.to_json.to_s)
Also move `to_json` inside `update_volume_options` function

2022-04-01 10:39 UTC, aravindavk commented on mgr/src/server/plugins/volume_option_set_reset.cr
> +  volume_option_keys = env.params.json["volume_option_keys"].as(Array)
```
volume_option_keys = Array(String).from_json(env.request.body.not_nil!)
```

2022-04-01 10:39 UTC, aravindavk commented on mgr/src/server/plugins/volume_option_set_reset.cr
> +  Datastore.update_volume_options(volume.id, volume.options.to_json.to_s)
Remove `to_json.to_s`

2022-04-01 10:39 UTC, aravindavk commented on volgen/src/moana_volgen.cr
> +
Extra change!

2022-04-01 10:39 UTC, aravindavk commented on mgr/src/server/datastore/volumes.cr
> +    connection.exec(query, options, volume_id)
```
connection.exec(query, options.to_json, volume_id)
```

2022-04-04 06:43 UTC, vatsa287 commented on clients/crystal/src/volumes.cr
> +    def set(volume_options : String)
done

2022-04-04 06:43 UTC, vatsa287 commented on clients/crystal/src/volumes.cr
> +        ({"volume_options": volume_options}).to_json,
done

2022-04-04 06:44 UTC, vatsa287 commented on clients/crystal/src/volumes.cr
> +    def reset(volume_option_keys : Array)
done

2022-04-04 15:33 UTC, aravindavk approved these changes

2022-04-04 15:34 UTC, aravindavk commented
Rebase is required.

2022-04-05 05:09 UTC, merged